# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: pyatv
email: pierre.staahl@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  a python client library for the Apple TV
url: "https://postlund.github.io/pyatv" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /pyatv
twitter_username: postlund
github_username:  postlund

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jemoji

pyatv_version: "pyatv==0.4.0a14"

top_pages:
  - link: /
    title: Main Page
  - link: /getting-started/
    title: Getting Started
  - link: /documentation/
    title: Documentation
  - link: /development/
    title: Development
  - link: /support/
    title: Support

page_links:
  documentation:
    - link: /documentation/
      title: Start
    - link: /documentation/concepts/
      title: Concepts
    - link: /documentation/protocols/
      title: Protocols
    - link: /documentation/atvremote/
      title: atvremote
  development:
    - link: /development/
      title: Start
    - link: /development/scan_pair_and_connect/
      title: Scan, Pair and Connect
    - link: /development/control/
      title: Control
    - link: /development/metadata/
      title: Metadata
    - link: /development/listeners/
      title: Listeners
    - link: /development/airplay/
      title: AirPlay
    - link: /development/api_reference/
      title: API Reference
    - link: /development/examples/
      title: Examples
  support:
    - link: /support/
      title: Start
    - link: /support/scanning_issues/
      title: Scanning Issues
    - link: /support/troubleshooting/
      title: Troubleshooting
    - link: /support/faq/
      title: FAQ


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
